document.getElementById('generate').addEventListener('click', () => {
    let authors = Object.keys(quotes);
    let author = authors[Math.floor(Math.random() * authors.length)];
    let quote = quotes[author];

    document.getElementById('quote').innerHTML = quote;
    document.getElementById('author').innerHTML = author;
});

const quotes = [
    {
    author: "poppy | EAT | 2021",
    quote: 'maybe today <br> i throw it all away <br> let my body eat itself and finally get its way'
    },
    {
    "poppy | EAT | 2021": 'i tell everyone that im okay <br> but im ashamed <br> im afraid <br> and it all eats at me ',
    "poppy | EAT | 2021": 'im not okay <br> i know that im not safe <br> could you come and eat me up and put me out my pain?',
    "elita | introverted | 2019": 'i dont hate you i just need some time alone',
    "waterparks | magnetic | 2021": 'but you said it im magnetic to the things i hate the most',
    "persona 4 | heartbeat, heartbreak | 2008": 'tell me why you did it <br> every dream falling apart <br> tell me why you did it <br> after the promise',
    "elita | introverted | 2019": 'im nervous observing <br> so determined its concerning <br> im a burden and im hurting <br> go easy on me Im learning',
    "jack off jill | fear of dying | 2000": 'im not afraid of standing still <br> im just afraid of being bored <br> im not afraid of speaking my mind <br> im just afraid of being ignored',
    "jack off jill | fear of dying | 2000": 'im not afraid of feeling <br> and im not afraid of trying im just afraid of losing <br> and i am afraid of dying',
    "jack off jill | fear of dying | 2000": 'im not afraid put the gun in my hand <br> im just afraid itll hurt like hell',
    "jack off jill | fear of dying | 2000": 'im not afraid of screaming <br> and im not afraid of crying <br> im just afraid of forgetting <br> and i am afraid of dying',
    "mindless self indulgence | never wanted to dance | 2008": 'there is nothing you can do that i have not already done to myself',
    "portal 2 | want you gone | 2011": 'oh how we laughed and laughed <br> except i wasnt laughing',
    "cam meekins | better days | 2013": 'i sing about you every way <br> cause youre the perfect melody <br> know the world aint perfect <br> but to me you were my everything',
    "CUCO | lover is a day | 2016": 'furthering my distance from you <br> realistically i cant leave now but im okay as long as you keep me from going crazy',
    "CUCO | lover is a day | 2016": 'ill take the bumpy road <br> itll probably break my legs <br> as long as i dont show you whats ruining my head',
    "hum | stars | 1995": 'i bring her home everything i want and nothing that she needs <br> i thought she would be there holding daisies <br> she always waits for me <br> she thinks she missed the train to mars <br> shes out back counting stars',
    "the zombies | the way i feel inside | 1965": 'should i try to hide <br> the way i feel inside my heart for you <br> would you say that you would try to love me too <br> in your mind could you ever be really close to me',
    "the zombies | the way i feel inside | 1965": 'but til i can see that you would really care for me <br> ill keep trying to hide the way i feel inside',
    "carpenters | two lives | 1983": 'maybe im a dreamer <br> maybe just a fool <br> lately i can hardly see the sun',
    "sorry | jealous guy | 2019": 'i dont wanna share your pretty heart with anybody else <br> im a selfish guy its only you me and myself <br> im a jealous guy dont want to see your pretty eyes with anybody else',
    "sorry | jealous guy | 2019": 'i want to be the one to serve you <br> i have to be the one who serves you',
    "BADBADNOTGOOD | time moves slow | 2016": 'time moves slow when youre all alone <br> and the time moves slow when youre out on your own <br> and the time moves slow when youre missing a friend <br> and the time moves slow when you came to the end',
    "BADBADNOTGOOD | time moves slow | 2016": 'running away is easy <br> its the leaving thats hard',
    "BADBADNOTGOOD | time moves slow | 2016": 'and loving you was easy <br> it was you leaving that scarred',
    "BADBADNOTGOOD | time moves slow | 2016": 'i knew just what you were thinking that day <br> you just didnt love me like i do <br> like i love you <br> the sad thing is were better off this way',
    "sammy rae | kick it to me | 2018": 'singing the blues all on my own in a dark room <br> nobody there all on my own in a dark room',
    "lady gaga | replay | 2020": 'who was it that pulled the trigger <br> was it you or i?',
    "lady gaga | replay | 2020": 'the monster inside you is torturing me <br> the scars on my mind are on replay',
    "lady gaga | replay | 2020": 'psychologically its something that i cant explain',
    "savlonic | epoch | 2016": 'i know we can make it better than it ever was',
    "savlonic | epoch | 2016": 'our fates are not yet written <br> i will take the warning <br> choose a way thats less destructive',
    "the living tombstone | my ordinary life | 2017": 'the people always different but it always feels the same',
    "the living tombstone | my ordinary life | 2017": 'staying still, eyes closed <br> let the world just pass me by',
    "the living tombstone | my ordinary life | 2017": 'lean in, let go <br> i feel fear for the very last time',
    "the living tombstone | my ordinary life | 2017": 'they tell me that im special <br> i smile and shake my head <br> ill give them stories to tell friends about the things i said',
    "the living tombstone | my ordinary life | 2017": 'they tell me im so humble <br> i say im turning red <br> they let me lie to them and dont feel like theyve been misled',
    "the living tombstone | my ordinary life | 2017": 'when you become untouchable youre unable to touch',
    "the living tombstone | i got no time | 2016": 'ive been staring at my death so many times',
    "the living tombstone | i got no time | 2016": 'i felt like i won <br> but i wasnt done <br> the nightmare repeats itself every time',
    "the living tombstone | i got no time | 2016": 'im getting sick from these apologies <br> from people with priorities <br> that their life matters so much more than mine',
    "the powerpuff girls | love makes the world go round | 1999": 'you cant hurt me with the things that you do <br> ill pick up dandelions and ill give them to you',
    "the powerpuff girls | you wanna make us feel real good | 2004": 'as i descend to the earth and i view the universe above me <br> i realize that life evolves revolves and dissolves completely around the opposites <br> therefore i conclude that i cannot exist in my utopian mind',
    "giga-p | drop pop candy | 2014": 'even when its raining i dont use an umbrella',
    "carpenters | i need to be in love | 1976": 'the hardest thing ive ever done is keep believing <br> theres someone in this crazy world for me',
    "carpenters | i need to be in love | 1976": 'the way that people come and go through temporary lives <br> my chance could come and i might never know',
    "carpenters | i need to be in love | 1976": 'it took awhile for me to learn that nothing comes for free <br> the price ive paid is high enough for me',
    "carpenters | i need to be in love | 1976": 'i know i ask perfection of a quite imperfect world <br> and fool enough to think thats what ill find',
    "carpenters | i need to be in love | 1976": 'here i am with pockets full of good intentions <br> but none of them will comfort me',
    "carpenters | i need to be in love | 1976": 'without a friend in sight <br> hanging on a hope but im alright',
    "persona 4 | heaven | 2008": 'cant get my mind out of those memories',
    "persona 4 | heaven | 2008": 'music keeps on turning me from the words that hurt my soul',
    "persona 4 | heaven | 2008": 'those long days passing by from that door <br> like late summer they slowly fade away',
    "carpenters | superstar | 1971": 'loneliness is such a sad affair <br> and i can hardly wait to be with you again',
    "carpenters | rainy days and mondays | 1974": 'sometimes id like to quit',
    "carpenters | rainy days and mondays | 1974": 'funny but it seems that its the only thing to do run and find the one who loves me',
    "carpenters | rainy days and mondays | 1974": 'what i feel has come and gone before <br> no need to talk it out',
    "carpenters | ill never fall in love again | 1971": 'what do you get when you fall in love <br> you only get lies and pain and sorrow',
    "carpenters | ill never fall in love again | 1971": 'dont tell me what its all about <br> cus ive been there and im glad im out',
    "carpenters | i wont last a day without you | 1972": 'day after day i must face a world of strangers where i dont belong',
    "carpenters | i wont last a day without you | 1972": 'when theres no getting over that rainbow <br> when my smallest of dreams wont come true <br> i can take all the madness the world has to give <br> but i wont last a day without you',
    "carpenters | all you get from love is a love song | 1976": 'now the tears in my eyes are ever blinding <br> the future that lies before me i cannot see <br> although tomorrow i know the sun is rising <br> lighting up the world for everyone but not for me',
    "death cab for cutie | ill follow you into the dark | 2014": 'love of mine <br> someday you will die <br> but ill be close behind <br> ill follow you into the dark',
    "death cab for cutie | ill follow you into the dark | 2014": 'if theres no one beside you when your soul embarks <br> then ill follow you into the dark',
    "death cab for cutie | ill follow you into the dark | 2014": 'well hold each other soon in the blackest of rooms',
    "death cab for cutie | soul meets body | 2005": 'i want to live where soul meets body <br> and let the sun wrap its arms around me <br> and bathe my skin in water cool and cleansing <br> and feel what its like to be new',
    "death cab for cutie | soul meets body | 2005": 'i do believe its true <br> that there are roads left in both of our shoes <br> but if the silence takes you then i hope it takes me too',
    "death cab for cutie | soul meets body | 2005": 'youre the only song i want to hear <br> a melody softly soaring through my atmosphere',
    "adele | skyfall | 2014": 'i know id never be me without the security of your loving arms',
    "johnny goth | panic | 2019": 'get me out of here <br> get me away',
    "mars argo | wasted away | 2014": 'wasted away again <br> warm milk dripping down my skin <br> your words running through my head <br> if im sick, im sad, im mad',
    "mars argo | wasted away | 2014": 'you might lie and i might cry <br> ill wipe my eyes, nevermind',
    "unaloon | CODEPENDENCY | 2019": 'im just as bad as you when im alone too',
    "unaloon | CODEPENDENCY | 2019": 'i convince myself im fine <br> but now that i can see <br> its just my codependency',
    "unaloon | CODEPENDENCY | 2019": 'please just speak to me <br> please just say you need me <br> please just speak to me <br> please just say you love me',
    "unaloon | CODEPENDENCY | 2019": 'tell me that youll be alright <br> so i wont have to deny that its all in me <br>that its just my codependency',
    "mars argo | using you | 2014": 'am i naive to think that he could be the love of my life? <br> there is a voice inside my head thats telling me that its right <br> i never thought id tell him how scared i am of losing him',
    "mars argo | using you | 2014": 'i dont care if i dont live to see another day <br> i love you in the worst way',
    "mars argo | runaway runaway | 2012": 'is there anybody listening? <br> eager words are making me an awful mess <br> you say you need me <br> were running out of time <br> i guess i fear the fear of consequence <br> you say youll leave me <br> but youll be sorry',
    "mars argo | runaway runaway | 2012": 'i wish i was a dumb pop star so the words wouldnt matter to you',
    "mars argo | runaway runaway | 2012": 'am i living an illusion? <br> i wanna runaway runaway runaway',
    "mars argo | runaway runaway | 2012": 'i feel like im losing control <br> maybe i should let myself go cus this is so predictable',
    "mars argo | runaway runaway | 2012": 'is there something that im missing? <br> my walls are caving in <br> i cant hear what youre saying <br> im afraid of giving in',
    "mars argo | love in black and white | 2011": 'i fell into a phase that im not fairly proud of when i first met my permanent frown',
    "mars argo | beauty is empty | 2011": 'your pretty smile is a monster and your beauty is empty',
    "mars argo | technology is a dead bird | 2009": 'i need to be myself again <br> i know precisely when its time to be the actor',
    "mars argo | technology is a dead bird | 2009": 'technology is a dead bird in your hands',
    "evanescence | hello | 2003": 'if i smile and dont believe <br> soon i know ill wake from this dream',
    "evanescence | hello | 2003": 'dont try to fix me im not broken <br> hello, im the lie living for you so you can hide',
    "poppy | dont ask | 2020": 'ill keep quiet cus the truth is getting too loud',
    "poppy | dont ask | 2020": 'ive given up too much to let this take me out',
    "poppy | dont ask | 2020": 'dont ask me how im feeling <br> theres nothing to talk about',
    "pink floyd | time | 1973": 'the time is gone <br> the song is over <br> thought id something more to say',
    "flatsound | i exist i exist i exist": 'look at me look at me look at me look at me <br> because i exist i exist i exist i exist i exist i exist',
    "now, now | thread | 2012": 'a hint of light in the dark <br> only enough to keep from giving up <br> if i could go back to the start to break the pattern forming between us',
    "now, now | wolf | 2012": 'i would kill to be your clothes <br> cling to your body and hang from your bones',
    "now, now | prehistoric | 2012": 'ill say that ive been trying to move on <br> we both know im not',
    "now, now | prehistoric | 2012": 'i would trade this sleep for you in a heartbeat',
    "now, now | prehistoric | 2012": 'each day you come closer <br> so close i can almost feel your breath on my shoulders <br> but i know if i turn around you might run away again',
    "now, now | school friends | 2012": 'she will be invisible like you want her <br> she will try to do everything just right for you',
    "now, now | school friends | 2012": 'you just like her where shes at <br> and youll thank her for the things she bought you <br> then youll go on your way',
    "now, now | school friends | 2012": 'the next day when you chase the other girl <br> she will remember all the things you said to her',
    "now, now | school friends | 2012": 'we can keep in touch if thats what you want <br> you can call me too if thats what friends do',
    "now, now | school friends | 2012": 'i am what you need when you cant find it somewhere else <br> i am what you want when you dont have anything else',
    "panucci's pizza | aesthetic? (more like ass-pathetic) | 2015": 'i wanna scoop out my cheeks so you cant pinch them anymore <br> i want to add to my legs and be as tall as the morgue <br> i want the fat in my arms to melt off my bones <br> and my stomach to fall out right onto the floor board',
    "panucci's pizza | aesthetic? (more like ass-pathetic) | 2015": 'arms, legs, gut, face <br> all of the things you love but i hate',
    "al bowlly | heartaches | 1931": 'heartaches, heartaches <br> my loving you meant only heartaches',
    "al bowlly | heartaches | 1931": 'heartaches, heartaches <br> what does it matter how my heart breaks',
    "al bowlly | heartaches | 1931": 'i should be happy with someone new <br> but my heart aches for you',
    "AJJ | body terror song | 2020": 'im so sorry that you have to have a body <br> one that will hurt you and be the subject of so much of your fear',
    "three days grace | pain | 2006": 'youre sick of feeling numb <br> youre not the only one',
    "three days grace | pain | 2006": 'this life is filled with hurt when happiness doesnt work',
    "three days grace | pain | 2006": 'id rather feel pain than nothing at all',
    "flyleaf | all around me | 2005": 'i can feel you all around me <br> thickening the air im breathing',
    "evanescence | missing | 2004": 'you wont cry for my absence <br> i know you forgot me long ago <br> am i that unimportant <br> am i so insignificant <br> isnt something missing? <br> isnt someone missing me?',
    "evanescence | missing | 2004": 'even though im the sacrifice <br> you wont try for me, not now <br> though id die to know you love me <br> im all alone',
    "evanescence | missing | 2004": 'and if i bleed, ill bleed knowing you dont care <br> and if i sleep just to dream of you <br> and wake without you there <br> isnt something missing?',
    "tupac | keep ya head up | 1993": 'forgive but dont forget <br> keep your head up',
    "bobby caldwell | what you won't do for love | 1978": 'my friends wonder what is wrong with me <br> well im in a daze from your love you see',
    "bobby caldwell | what you won't do for love | 1978": 'what you wont do do for love <br> you tried everything but you dont give up <br> in my world only you make me do for love what i would not do',
    "grover washington jr. & bill withers | just the two of us | 1980": 'we look for love no time for tears <br>wasted waters all that is and it dont make no flowers grow',
    "grover washington jr. & bill withers | just the two of us | 1980": 'good things might come to those who wait <br> not for those who wait too late',
    "grover washington jr. & bill withers | just the two of us | 1980": 'just the two of us <br> we can make it if we try',
    "mac demarco | treat her better | 2014": 'treat her better boy <br> if having her at your sides something you enjoy <br> if having her in your lifes really so important to you now',
    "daryl hall & john oates | she's gone | 1974": 'think ill spend eternity in the city <br> let the carbon and monoxide choke my thoughts away <br> and pretty bodies help dissolve the memories <br> they can never be what she was to me',
    "little river band | reminiscing | 1978": 'i want to build my world around you',
    "little river band | reminiscing | 1978": 'i said to myself when we are old <br> we will go dancing in the dark <br> walking through the park and reminiscing',
    "karen carpenter | if i had you | 1989": 'if i had you i wouldnt need the sun to light the morning <br> if i could have your love to light my night id never for a second keep our love from burning bright',
    "karen carpenter | if i had you | 1989": 'if i had you again i wouldnt be the fool ive been <br> if i had you again id never let the loving end',
    "karen carpenter | if i had you | 1989": 'so say that you believe in second chances <br> and say youll let me be with you tonight <br> if youll take my hand ill show you just how love could be so right',
    "bobby caldwell | my flame | 1978": 'my flame, some things will never change <br> i still hold your vision in my hand <br> say you still love me',
    "poppy | am i a girl? | 2018": 'please dont complicate me <br> i dont understand <br> sometimes im feminine <br> sometimes im masculine',
    "poppy | am i a girl? | 2018": 'dont evaluate me as woman or man <br> its keeping me awake <br> cant differentiate',
    "poppy | am i a girl? | 2018": 'am i girl? <br> am i boy? <br> am i a girl? <br> what does that even mean? <br> im somewhere in between',
    "TV girl | not allowed | 2016": 'wish that it was me <br> i guess its different cus you love him <br> but ive got an interactive sick and twisted imagination <br> and thats gotta count for something',
    "TV girl | not allowed | 2016": 'i hope were still friends <br> yeah i hope you dont mind',
    "cherish | chemical x | 2003": 'beware of the powerpuff girls',
    "meg & dia | monster | 2006": 'he battered his tiny fists to feel something <br> wondered what its like to touch and feel something',
    "meg & dia | monster | 2006": 'monster <br> how should i feel?',
    "meg & dia | monster | 2006": 'he slowly saw their nightmares were his dreams',
    "meg & dia | monster | 2006": 'turn the sheets down <br> murder ears with pillow lace <br> theres bath tubs full of glow flies <br> bathe in kerosene',
    "poppy | flux | 2021": 'my body is fluid cus ive been through it all <br> chewed up and used its cut into pieces to feed them all',
    "poppy | flux | 2021": 'when i see red, i go <br> and the serotonin will flow <br> and theres no bandage to lessen the damage',
    "poppy | on the level | 2021": 'right into traffic driving straight through every light ive got a habit of ignoring obvious signs',
    "poppy | hysteria | 2021": 'cant contain my emotions theres <br> no box big enough to hold them',
    "poppy | her | 2021": 'run your mouth to keep her scared <br> you expected her to care <br> but when her mind made up you were illfully prepared',
    "poppy | as strange as it seems | 2021": 'i was a passenger in a speeding car <br> you showed no regard for me',
    "poppy | as strange as it seems | 2021": 'i was a careful girl with a broken heart <br> you showed no regard for me',
    "poppy | as strange as it seems | 2021": 'im hanging on the steering wheel of a speeding car <br> ive got no regard for me',
    "poppy | never find my place | 2021": 'tonight ill eat my brain and maybe find a resolution <br> tonight ill cure my pain',
    "eels | your lucky day in hell | 1998": 'years go by <br> still i dont know who shall inherit this earth <br> and no one will know my name until its on a stone',
    "the living tombstone | i got no time | 2016": 'im regretting having memories of my friends <br> who they used to be <br> beside me before they left me to die',
    "the living tombstone | i got no time | 2016": 'i have this urge to kill and show that im alive <br> im getting sick from these apologies <br> from people with priorities that their life matters so much more than mine',
    "the living tombstone | i got no time | 2016": 'im stuttering again <br> no one will listen and no one will understand <br> because im crying as much as i speak',
    "built to spill | big dipper | 1994": 'you should have been here last night and heard what the big dipper said to me',
    "inabakumori feat. kaai yuki | ラグトレイン (lag train) | 2020": 'i wheeze out a pained breath as i sleep and fake my way through this ever lengthening day',
    "connor spioto | the villain i appear to be | 2017": 'i assure you before you can find me im gone <br> so come on and catch me youve still got a chance',
    "connor spioto | the villain i appear to be | 2017": 'although i may not think everything through <br> i dont take back what i say or regret what i do',
    "connor spioto | the villain i appear to be | 2017": 'even if you cant see the good inside me <br> i dont have the time to tell you why i do the things that i do',
    "connor spioto | the villain i appear to be | 2017": 'please hold on and soon youll see <br> that im not the villain i appear to be',
    "connor spioto | the villain i appear to be | 2017": 'i know you think im crazy <br> but i hope that maybe now youll see why i had to try',
    "teddyloid | fly away | 2010": 'heart stood still when we first met <br> i thought wed be together yet youre using me for your own gain <br> and now ill never feel the same',
    "teddyloid | fly away | 2010": 'youll never find a better time make your stand youll be fine',
    "mag.lo | who am i? | 2016": 'is this a dream or a waking fucking nightmare?',
    "mag.lo | who am i? | 2016": 'at the tip of my wand i could write songs <br> but why write <br> why bother',
    "13 the musical | what it means to be a friend | 2008": 'a friend is the person who most of all cares about what you feel <br> and nothing is harder than learning a friend isnt real',
    "13 the musical | if that's what it is | 2008": 'lets face it youve worked so hard and now youre scarred and free of any hope',
    "13 the musical | if that's what it is | 2008": 'if thats what it is then thats what it is <br> though thats not the way i choose to see it',
    "13 the musical | if that's what it is | 2008": 'i make my own rules <br> i do what i can <br> if i hit the wall then maybe its all part of the plan',
    "13 the musical | if that's what it is | 2008": 'tomorrow will come <br> today will be gone <br> and so i put one foot in front of the other',
    "13 the musical | if that's what it is | 2008": 'i say i wont cry <br> i cry until dawn <br> and then i put one foot in front of the other',
    "13 the musical | if that's what it is | 2008": 'i face the world for what it is and not what i wish it could be',
    "13 the musical | if that's what it is | 2008": 'one day ill be thirty <br> one day ill be fine <br> one day ill make fun of this dramatic life of mine',
    "13 the musical | a little more homework | 2008": 'one day ill be older and then ill write a book about the choices that i made',
    "13 the musical | a little more homework | 2008": 'ill choose what to say <br> what to see when presented with a candy coated opportunity',
    "13 the musical | a little more homework | 2008": 'so you gotta hang in there til the whole story ends <br>cus we all have a little more homework to do',
    "mean girls the musical | what's wrong with me | 2018": 'tell me whats wrong with me <br> my body face my hair tell me <br> all my many faults <br> tell me like you care',
    "mean girls the musical | what's wrong with me | 2018": 'when we both know youre cruel and we both know youre right <br> i could listen to you like a fool all night',
    "mean girls the musical | what's wrong with me | 2018": 'mama called me beautiful <br> dont believe her anymore <br> now im listening to you',
    "13 the musical | a little more homework | 2008": 'the sky goes blue and the sky goes black and no matter what you do you cant go back',
    "mean girls the musical | what's wrong with me | 2018": 'whats wrong with me <br> wheres my mind <br> where does it end',
    "flyleaf | all around me | 2005": 'i can feel you all around me thickening the air im breathing <br> holding onto what im feeling <br> savouring this heart thats healing',
    "flyleaf | all around me | 2005": 'you said you would never leave me <br> i believe you <br> i believe',
    " ": 'step into my mind youll last two seconds then youre gone demons in my penthouse know the words to all my songs',
    " ": 'in all my searching theres one thing that i found we dont go to heaven we just rot inside the ground',
    " ": 'and you dont seem to understand a shame you seemed an honest man',
    " ": 'and you know what they say might hurt you and you know that it means so much and you dont even feel a thing',
    " ": 'i am falling i am fading i am drowning help me to breathe i am hurting i have lost it all i am losing',
    " ": 'and you dont seem the lying kind a shame that i can read your mind',
    " ": 'please understand if love ends then i promise you that i shall never breathe again',
    " ": 'i cant get you out of my head and i know i cant pretend that i wont die if you decide you wont see me again',
    " ": 'when i die fuck it i wanna go to hell cus im a piece of shit it aint hard to fuckin tell',
    " ": 'i wonder if i died would tears come to her eyes forgive me for my disrespect forgive me for my lies',
    " ": 'chasing after you is like a fairytale but i feel like im glued on tight to this carousel',
    " ": 'its no fun when im sitting all alone youre right in front of me and im done with your bittersweet bittersweet tragedy',
    " ": 'tell me why the hell no one is here tell me what to do to make it all feel better maybe its a cruel joke one me whatever whatever',
    " ": 'maybe if i know all of them well i wouldnt have been trapped inside this hell that holds me',
    " ": 'cant take it anymore need to put you to bed sing you a lullaby where you die in the end',
    " ": 'im peeling the skin off my face cus i really hate feeling safe',
    " ": 'im not a piece of cake for you to just discard while you walk away',
    " ": 'beauty queen of only eighteen she had some trouble with herself he was always there to help her she always belonged to someone else',
    " ": 'i dont mind spending every day out in your corner in the pouring rain',
    " ": 'im obsessed with you in a way i cant believe when you wipe your tears do you wipe them just for me',
    " ": 'and even if i was wrong i know i dont deserve this',
    " ": 'im lying on the moon my dear ill be there soon',
    " ": 'all i want is you now all i wanna do now is wait for you to call me baby im so sorry do you wanna hurt me are you gonna hurt me please dont desert me',
    " ": 'but even if he were my man hed never truly understand what it means to be a girl',
    " ": 'put ribbons in my curls then carry around a knife with my diamonds its psycho',
    " ": 'trade it all for a false self insecurity fall in love fall in line with all his fantasies',
    " ": 'fake it til we make everyone happy but ourselves use us for our bodies til theres nothing but a shell',
    " ": 'i was born and raised as an eastern girl in a western world i was told to choose to be what i chose to be there doesnt seem to be a place for me',
    " ": 'you should be able to feel a performance with your whole body and soul',
    " ": 'i reflect on my reflection and i ask myself the question whats the right direction to go i dont know',
    " ": 'im always running out of time i think ive made up my mind',
    " ": 'everything that i believed in turned out to be such a stupid fantasy a reflection of how i wanted things to be im ending everything i know screaming out in pain might as well rip out my throat much too fast i will sing and cry this is my goodbye',
    " ": 'i cant abandon the fantasy that i know everything you see about me is only show heart is exhausted and weak but im not afraid all i can do now i watch as i fade away',
    " ": 'as for the strength and the will left inside of me im just a kid i dont know what you want from me',
    " ": 'one by one after another my memories start to delete ill never retrieve them but theyll never take away my memories of you times that we laughed and the fun things we used to do all i can hope is that you wont forget them too',
    " ": 'nowadays when i try to sing i can feel my body rip at the seams desperately praying for some kind of miracle no one listens im all alone',
    " ": 'everything that i protected turned out to be a delusion in the end stabbing me with the love ill never have again if i tried saying how i feel would that even reach you before i disappeared not enough time to sing or cry this is my goodbye',
    " ": 'this is the end of me soon i wont know im gone fading away from here until theres nothing left its so pathetic right now that i think of it only the memories of my voice will remain',
    " ": 'you might forget me but please dont forget my name if that alone could come true i can rest in peace lasting forever like how i was supposed to be this is the end now but i like to think someday that even if i die this song will still remain',
    " ": 'thank you so much and finally goodbye for good',
    " ": 'watch me fault her youre living like a disaster she said kill me faster with strawberry gashes all over',
    " ": 'called her over and asked her if she was improving she said feels fine its wonderful wonderful here hex me told her i dreamt of a devil that knew her',
    " ": 'i lay quiet waiting for her voice to say some things you lose and some things you just give away scold me failed her if only id held on tighter to her pale white skin that twisted and withered away from me way from me',
    " ": 'watch me lose her its almost like losing myself give her my soul and let them take somebody else',
    " ": 'when i step onto the stage see the curtain raise im apparent ive got someone to play all the crowds are in the seats looking straight at me for an answer they just get what they see',
    " ": 'every time it all comes down in the end thats a truth that the stage school doesnt teach you but its good to know',
    " ": 'it takes much more than just learning a script you see you gotta take the part and believe it i sometimes make up all of my lines on the spot but i will always give what i got',
    " ": 'i thought i was only acting but i felt exactly like it was all for real i sure didnt know it hurt so but then no rehearsal could show you how to feel inside what you gotta hide where to put your pride when to realize youve had your time find another role carry on the show',
    " ": 'so far it occurs to me that everybody in the world is afraid of me just one more sin and down we go but the news is out and i think im going to kill myself or fuck myself or tell myself about the only thing that matters now',
    " ": 'this planet isnt special collections made of clay im waiting for the punishment i know is on my way cut cut cut me up and fuck fuck fuck me up',
    " ": 'somewhere on a toilet wall i read the words you form a line to formalize the former lies and i finally saw the truth something so profound and it was sitting there surrounded by the garbage and the stains another victim of the refuse',
    " ": 'please please forgive me but i wont be home again maybe someday youll look up and barely conscious youll say to no one isnt something missing',
    " ": 'you wont cry for my absence i know you forgot me long ago am i that unimportant am i so insignificant isnt something missing isnt someone missing me',
    " ": 'even though im the sacrifice you wont try for me not now though id die to know you love me im all alone',
    " ": 'and if i bleed ill bleed knowing you dont care and if i sleep just to dream of you ill wake without you there',
    " ": 'now i will tell you what ive done for you fifty thousand years ive cried screaming deceiving and bleeding for you and you still wont hear me',
    " ": 'dont want you hand this time ill save myself maybe ill wake up for once',
    " ": 'i wanna be the true savior the one with the terrible demise',
    " ": 'i wanna be your true love im the only one you could cry to all the time i could just be who you need darling wont you just plead or should i begin to bleed',
    " ": 'ill tear down the sky what do you want ill do it all for life my love my alibi tonight ill try to do it for you',
    " ": 'i wanna be a white angel the one with two billion of eyes i wanna be like a fly on the wall to watch you until you die im gonna be where you are doesnt matter how far because we are meant to be',
    " ": 'im not a fan of puppeteers but ive a nagging fear someone else is pulling at the strings',
    " ": 'a terrible catastrophe played by your symphony what a terrifying work of art',
    " ": 'you just dont know it yet but you love me and i love you the same one day well have a pretty wedding and ill be your everything well be together yes forever we will never ever part you dont know it yet but baby ive already got your heart',
    " ": 'last night goodnight this night ill hold you hand tight and go to sleep goodnight',
    " ": 'itd be wonderful if i could spend morning with you once more i just wish even such a small hope can be made a miracle',
    " ": 'when i think that the end will arrive someday thats when i hope that the night sky will keep your smile goodnight',
    " ": 'if it wasnt for you i could sleep forever but im not mad i want breakfast',
    " ": 'happy thoughts happy thoughts happy thoughts in bottles all in a row',
    " ": 'sometimes my friend feels a certain way down comes a bottle to save the day',
    " ": 'night after night more dreams friend after friend more bottles',
    " ": 'holding them out to each and every friend each and every bottle but every time i let one go it shatters against the tile between my feet happy thoughts happy thoughts happy thoughts in shards all over the floor',
    " ": 'a poem is never actually finished it just stops moving',
    " ": 'i mean i only tried to laugh along because i was being laughed at so why did they get angry at me',
    " ": 'when things dont go as well as they do in my imagination why do i always have to say im sorry',
    " ": 'ive mastered the art of whiling away my time by pretending to sleep so much that i turned to stone and stopped breathing',
    " ": 'a useless loving tool that was never painted in any colour even when i got down on my knees and tolerated everything nothing came to save me isnt this too much havent i been left out is that right',
    " ": 'i mean even if you try to blame your sins and such on this tiny tiny world full of lies and curse it will that blame make things better or worse',
    " ": 'its not like its selfish or anything to want you to believe from the bottom of your heart that im adorable',
    " ": 'viva viva happy i cry big tears all night all night all by myself',
    " ": 'a perplexing thing called love took over and then i couldnt keep my heart space from splitting in two never had the capacity to control it in the first place',
    " ": 'everyday is full of why did this did that but in the end its sayonara baby',
    " ": 'a blades edge with centimeters of suspicion stabbing a vein at the end of it all sickly love spurts out',
    " ": 'each night i went to sleep wishing that this would turn out to be a nightmare <br> yet each morning i awoke to find that the world was just as horribly warped as it was the day before'
}]